"""initial

Revision ID: 0001
Revises: 
Create Date: 2026-04-20 20:57:51.198593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('eli_uri', sa.Text(), nullable=False),
    sa.Column('act_type', sa.Enum('KONSTITUTSIYA', 'KODEKS', 'ZAKON', 'NAREDBA', 'PRAVILNIK', 'POSTANOVLENIE', 'UKAZ', 'RESHENIE_KS', 'RESHENIE_NS', name='act_type'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('title_short', sa.Text(), nullable=True),
    sa.Column('number', sa.Text(), nullable=True),
    sa.Column('adoption_date', sa.Date(), nullable=True),
    sa.Column('dv_broy', sa.Integer(), nullable=False),
    sa.Column('dv_year', sa.Integer(), nullable=False),
    sa.Column('dv_position', sa.Integer(), nullable=False),
    sa.Column('issuing_body', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('IN_FORCE', 'REPEALED', 'PARTIALLY_IN_FORCE', name='act_status'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dv_broy', 'dv_year', 'dv_position'),
    sa.UniqueConstraint('eli_uri')
    )
    op.create_table('amendment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('amending_work_id', sa.UUID(), nullable=False),
    sa.Column('target_work_id', sa.UUID(), nullable=False),
    sa.Column('target_e_id', sa.Text(), nullable=True),
    sa.Column('operation', sa.Enum('INSERTION', 'SUBSTITUTION', 'REPEAL', 'RENUMBERING', name='amendment_op'), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['amending_work_id'], ['work.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_work_id'], ['work.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expression',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('work_id', sa.UUID(), nullable=False),
    sa.Column('expression_date', sa.Date(), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('akn_xml', sa.Text(), nullable=False),
    sa.Column('source_file', sa.Text(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['work.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_id', 'expression_date', 'language')
    )
    op.create_table('external_id',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('work_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('LEX_BG', 'PARLIAMENT_BG', 'DV_PARLIAMENT_BG', name='external_source'), nullable=False),
    sa.Column('external_value', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['work_id'], ['work.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_id', 'source')
    )
    op.create_table('element',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('expression_id', sa.UUID(), nullable=False),
    sa.Column('e_id', sa.Text(), nullable=False),
    sa.Column('parent_e_id', sa.Text(), nullable=True),
    sa.Column('element_type', sa.Enum('PART', 'TITLE', 'CHAPTER', 'SECTION', 'ARTICLE', 'PARAGRAPH', 'POINT', 'LETTER', 'HCONTAINER', name='element_type'), nullable=False),
    sa.Column('num', sa.Text(), nullable=True),
    sa.Column('heading', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['expression_id'], ['expression.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expression_id', 'e_id')
    )
    op.create_table('reference',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_expression_id', sa.UUID(), nullable=False),
    sa.Column('source_e_id', sa.Text(), nullable=False),
    sa.Column('target_work_id', sa.UUID(), nullable=True),
    sa.Column('target_e_id', sa.Text(), nullable=True),
    sa.Column('reference_type', sa.Enum('CITES', 'DEFINES', name='reference_type'), nullable=False),
    sa.ForeignKeyConstraint(['source_expression_id'], ['expression.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_work_id'], ['work.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reference')
    op.drop_table('element')
    op.drop_table('external_id')
    op.drop_table('expression')
    op.drop_table('amendment')
    op.drop_table('work')
    # ### end Alembic commands ###
